hadrware:
  comport: COM3
  baudrate: 115200
  timeout: 10
actuator:
  axis: A
  steps_per_mm: 10078.74
  acceleration: 40.0
  max_speed: 250.0
  homing_feed: 50
  homing_seek: 150
  homing_pulloff: 5
  pull_back: -7.5
  jog_length_rough: 0.1
  jog_length_fine: 0.01
  jog_length_speed: 100
  jog_position: 4.269
power:
  motor_drive_power: 31
  motor_idle_power: 10
  send_motor_power_on_init: false
motion:
  rapid_drive_speed: 250.0
  drive_speed: 50.0
  steps: 5.0
  return_home_after_complete: true
  keypoints:
  - -0.309
  - 4.269
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
shutter:
  pre_shutter_wait: 1.0
  frames_to_capture_per_step: 1
  shutter_press_time: 0.5
  post_shutter_wait_time: 0.5
generated_gcode:
- ; Generator version 0.1.0
- ; Set absolute movement mode
- G90
- ''
- ; Move to start position
- G1 A-0.309 F250.0
- ''
- ; Set relative movement mode
- G91
- ''
- ''
- ; ----------- NEW STEP ---------------
- ; Wait till platform is stable
- G4 P1.0
- ; Trigger shutter
- M8
- ; Capturing...
- G4 P0.5
- ; Retract shutter
- M9
- ; Wait post trigger
- G4 P0.5
- ''
- ; ----------- NEW STEP ---------------
- ; Moving by 0.9156000000000001mm
- G1 A0.9156000000000001 F50.0
- ; Wait till platform is stable
- G4 P1.0
- ; Trigger shutter
- M8
- ; Capturing...
- G4 P0.5
- ; Retract shutter
- M9
- ; Wait post trigger
- G4 P0.5
- ''
- ; ----------- NEW STEP ---------------
- ; Moving by 0.9156000000000001mm
- G1 A0.9156000000000001 F50.0
- ; Wait till platform is stable
- G4 P1.0
- ; Trigger shutter
- M8
- ; Capturing...
- G4 P0.5
- ; Retract shutter
- M9
- ; Wait post trigger
- G4 P0.5
- ''
- ; ----------- NEW STEP ---------------
- ; Moving by 0.9156000000000001mm
- G1 A0.9156000000000001 F50.0
- ; Wait till platform is stable
- G4 P1.0
- ; Trigger shutter
- M8
- ; Capturing...
- G4 P0.5
- ; Retract shutter
- M9
- ; Wait post trigger
- G4 P0.5
- ''
- ; ----------- NEW STEP ---------------
- ; Moving by 0.9156000000000001mm
- G1 A0.9156000000000001 F50.0
- ; Wait till platform is stable
- G4 P1.0
- ; Trigger shutter
- M8
- ; Capturing...
- G4 P0.5
- ; Retract shutter
- M9
- ; Wait post trigger
- G4 P0.5
- ''
- ; Set absolute movement mode
- G90
- ; Move to start position
- G1 A-0.309 F250.0
